name       : radare2
version    : 4.5.1
release    : 16
homepage   : https://radare.org/
source     :
    - https://github.com/radareorg/radare2/releases/download/4.5.1/radare2-src-4.5.1.tar.gz : 82b1c876224bec6846780e2582cdc6c534cb6dfc3df484bf88f034ab4f595f95
license    : LGPL-3.0-or-later
component  : programming.tools
summary    : Unix-like reverse engineering framework and commandline tools
description: |
    r2 is a rewrite from scratch of radare in order to provide a set of libraries and tools to work with binary files.
builddeps  :
    - pkgconfig(capstone)
    - pkgconfig(liblz4)
    - pkgconfig(libuv)
    - pkgconfig(libxxhash)
    - pkgconfig(libzip)
    - pkgconfig(tree-sitter)
setup      : |
    %meson_configure \
        -Dchecks_level=1 \
        -Denable_r2r=false \
        -Denable_tests=false \
        -Duse_sys_capstone=true \
        -Duse_sys_lz4=true \
        -Duse_sys_magic=true \
        -Duse_sys_openssl=true \
        -Duse_sys_tree_sitter=true \
        -Duse_sys_xxhash=true \
        -Duse_sys_zip=true \
        -Duse_sys_zlib=true
build      : |
    %ninja_build
install    : |
    %ninja_install
    ln -s /usr/bin/radare2 $installdir/usr/bin/r2
