name       : rizin
version    : 0.1.2
release    : 17
source     :
    - https://github.com/rizinorg/rizin/releases/download/v0.1.2/rizin-src-0.1.2.tar.xz : 9e9529f302622806902928a05ed9dd8492d3278fa9c85a9ad05c032c1a91fec1
license    : LGPL-3.0-or-later
component  : programming.tools
homepage   : https://rizin.re/
summary    : UNIX-like reverse engineering framework and command-line toolset
description: |
    A free and open-source Reverse Engineering framework, providing a complete binary analysis experience with features like Disassembler, Hexadecimal editor, Emulation, Binary inspection, Debugger, and more.
replaces   :
    - radare2
    - devel :
        - radare2-devel
builddeps  :
    - pkgconfig(capstone)
    - pkgconfig(liblz4)
    - pkgconfig(libuv)
    - pkgconfig(libxxhash)
    - pkgconfig(libzip)
    - pkgconfig(tree-sitter)
setup      : |
    %meson_configure \
        -Dchecks_level=1 \
        -Denable_rz_test=false \
        -Denable_tests=false \
        -Duse_sys_capstone=true \
        -Duse_sys_lz4=true \
        -Duse_sys_magic=true \
        -Duse_sys_openssl=true \
        -Duse_sys_tree_sitter=true \
        -Duse_sys_xxhash=true \
        -Duse_sys_zip=true \
        -Duse_sys_zlib=true
build      : |
    %ninja_build
install    : |
    %ninja_install
