name       : radare2
version    : 4.5.0
release    : 14
homepage   : https://radare.org/
source     :
    - https://github.com/radareorg/radare2/releases/download/4.5.0/radare2-src-4.5.0.tar.gz : 255bc3530d86f262a91f6d45e297f6a239f700106d89d9b4cab80cef6187c86c
license    : LGPL-3.0-or-later
component  : programming.tools
summary    : Unix-like reverse engineering framework and commandline tools
description: |
    r2 is a rewrite from scratch of radare in order to provide a set of libraries and tools to work with binary files.
builddeps  :
    - pkgconfig(capstone)
    - pkgconfig(liblz4)
    - pkgconfig(libuv)
    - pkgconfig(libxxhash)
    - pkgconfig(libzip)
    - pkgconfig(tree-sitter)
setup      : |
    %patch -p1 < $pkgfiles/Fix-missing-grep-glitch-in-r2pm.patch
    %meson_configure \
        -Dchecks_level=1 \
        -Denable_tests=false \
        -Denable_r2r=false \
        -Duse_sys_capstone=true \
        -Duse_sys_lz4=true \
        -Duse_sys_magic=true \
        -Duse_sys_openssl=true \
        -Duse_sys_tree_sitter=true \
        -Duse_sys_xxhash=true \
        -Duse_sys_zip=true \
        -Duse_sys_zlib=true
build      : |
    %ninja_build
install    : |
    %ninja_install
    ln -s /usr/bin/radare2 $installdir/usr/bin/r2
