name       : radare2
version    : 3.8.0
release    : 6
homepage   : https://radare.org/
source     :
    - https://github.com/radare/radare2/archive/3.8.0.tar.gz : 09496070458c02f04b63932839aba341ab64417c676cfc649a8e754e435952e1
license    : LGPL-3.0-or-later
component  : programming.tools
summary    : Unix-like reverse engineering framework and commandline tools
description: |
    r2 is a rewrite from scratch of radare in order to provide a set of libraries and tools to work with binary files.
builddeps  :
    - pkgconfig(capstone)
    - pkgconfig(liblz4)
    - pkgconfig(libuv)
    - pkgconfig(libzip)
    - xxhash-devel
setup      : |
    %meson_configure \
        -Dchecks_level=1 \
        -Duse_sys_capstone=true \
        -Duse_sys_lz4=true \
        -Duse_sys_magic=true \
        -Duse_sys_openssl=true \
        -Duse_sys_xxhash=true \
        -Duse_sys_zip=true \
        -Duse_sys_zlib=true
build      : |
    %ninja_build
install    : |
    %ninja_install
    ln -s /usr/bin/radare2 $installdir/usr/bin/r2
