name       : radare2
version    : 3.6.0
release    : 4
source     :
    - https://github.com/radare/radare2/archive/3.6.0.tar.gz : a763d3812a4cec74fd39d67a2559a4e0073e9e8d1d55481e5feb3f00bbe19b02
license    : LGPL-3.0-or-later
component  : programming.tools
summary    : Unix-like reverse engineering framework and commandline tools
description: |
    r2 is a rewrite from scratch of radare in order to provide a set of libraries and tools to work with binary files.
builddeps  :
    - pkgconfig(capstone)
    - pkgconfig(liblz4)
    - pkgconfig(libuv)
    - pkgconfig(libzip)
    - xxhash-devel
setup      : |
    %meson_configure \
        -Dchecks_level=1 \
        -Duse_sys_capstone=true \
        -Duse_sys_lz4=true \
        -Duse_sys_magic=true \
        -Duse_sys_openssl=true \
        -Duse_sys_xxhash=true \
        -Duse_sys_zip=true \
        -Duse_sys_zlib=true
build      : |
    %ninja_build
install    : |
    %ninja_install
